blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/raquezha/codesnapper/discussions
    about: Ask questions, share ideas, or discuss the project
  - name: 📖 Documentation
    url: https://github.com/raquezha/codesnapper/blob/main/README.md
    about: Read the full documentation and API reference

