name: 🚀 Feature Request
description: Suggest a new feature for Code Snapper
title: "[FEATURE] "
labels: ["enhancement", "feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the details below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - API Enhancement
        - Image Rendering
        - Design System
        - Configuration
        - Testing
        - Documentation
        - Infrastructure
        - Other
    validations:
      required: true

  - type: checkboxes
    id: design-systems
    attributes:
      label: Design Systems
      description: Which design systems should this feature support?
      options:
        - label: macOS Style
        - label: Material Design
        - label: Both (preferred)

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used? What problem does it solve?
      placeholder: Describe the use case or problem this feature would solve...

  - type: textarea
    id: api-example
    attributes:
      label: API Example (if applicable)
      description: Show how this feature would work in the API
      placeholder: |
        ```json
        {
          "code": "example",
          "newParameter": "value"
        }
        ```

  - type: checkboxes
    id: checklist
    attributes:
      label: Implementation Checklist
      description: What needs to be implemented? (check all that apply)
      options:
        - label: API endpoint changes
        - label: Request/response models
        - label: Image rendering updates
        - label: Input validation
        - label: Tests
        - label: Documentation updates
