name: ⚡ Ready to Code
description: Quick-win tasks ready for implementation
title: "[READY] "
labels: ["good first issue", "ready-to-code", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🚀 **This task is ready to code!** All requirements are defined and it's a great task for contributors.

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: What needs to be implemented?
      placeholder: Clear description of what to build...
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: How complex is this task?
      options:
        - Beginner (30-60 minutes)
        - Intermediate (1-3 hours)
        - Advanced (half day)
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] API accepts new parameter
        - [ ] Feature works with both design systems
        - [ ] Tests added
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: implementation-hints
    attributes:
      label: Implementation Hints
      description: Technical guidance for implementation
      placeholder: |
        - Files to modify: `src/main/kotlin/...`
        - Existing code to reference: `ImageConfiguration.lightTheme()`
        - Add validation in: `InputValidationService`

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: Show the expected API usage
      placeholder: |
        ```json
        {
          "code": "fun hello() = println(\"World\")",
          "language": "kotlin",
          "newParameter": "expectedValue"
        }
        ```
    validations:
      required: true

  - type: checkboxes
    id: design-systems
    attributes:
      label: Design System Support
      description: Which design systems need this feature?
      options:
        - label: macOS Style (required)
          required: true
        - label: Material Design (required)
          required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Requirements
      description: How should this be tested?
      placeholder: |
        - Unit tests for new functionality
        - Integration test for API endpoint
        - Manual testing with both design systems
